server:
  port: 8080

spring:
  application:
    name: frontend-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka

zuul:
  routes:
    camp: /camp/**
    arena: /arena/**
    promoter: /promoter/**
