# Use this file for configuration during development. Note that properties in this file wil not overwrite properties in
# the config-files folder. When you are done testing your changes, move them to the corresponding file in the
# config-files folder