spring:
  data:
    rest:
      return-body-on-create: true
      return-body-on-update: true

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8090/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh
